import { mobileConfig } from './config.js';
import { supabase } from './supabase.js';
import './email-scan-review-panel.css';

interface Connection { id:string; provider:string; status:string }
interface ScanItem {
  id:string; subject:string; senderDomain:string|null; receivedAt:string; processingStatus:string;
  validationStatus:string|null; eventType:string|null; merchant:string|null; orderNumber:string|null;
  total:number|null; currency:string|null; confidence:number|null; productCount:number; reasons:string[];
  state:'in_buyflow'|'can_add'|'related_unlinked'|'uncertain_order'|'not_purchase'; canAdd:boolean;
  linkedPurchase:null|{id:string;merchantName:string|null;orderNumber:string|null;currentState:string;relationType:string};
}
interface AuditResponse {
  windowDays:number; query:string;
  audit:null|{id:string;status:string;processedAt:string|null;errorCode:string|null;result:Record<string,number>|null};
  summary:{totalVisible:number;inBuyFlow:number;canAdd:number;relatedUnlinked:number;uncertain:number;notPurchase:number};
  items:ScanItem[];
}

function escapeHtml(value:unknown):string{return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('hu-HU',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function formatMoney(amount:number|null,currency:string|null){if(amount===null)return null;try{return new Intl.NumberFormat('hu-HU',{style:'currency',currency:currency||'HUF',maximumFractionDigits:currency==='HUF'?0:2}).format(amount)}catch{return `${amount} ${currency||''}`.trim()}}

async function token(){const {data}=await supabase.auth.getSession();if(!data.session)throw new Error('SESSION_REQUIRED');return data.session.access_token}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const access=await token();const res=await fetch(`${mobileConfig.apiBaseUrl}${path}`,{...init,headers:{Authorization:`Bearer ${access}`,Accept:'application/json',...(init.body?{'Content-Type':'application/json'}:{}),...(init.headers??{})}});if(!res.ok)throw new Error(`API_${res.status}`);return await res.json() as T}
async function activeConnection():Promise<Connection|null>{const data=await request<{connections:Connection[]}>('/api/email-connections');return data.connections.find(c=>c.provider==='nylas'&&c.status==='active')??null}

function close(){document.querySelector('#buyflow-scan-review-overlay')?.remove()}
function stateLabel(item:ScanItem){if(item.state==='in_buyflow')return ['BuyFlowban','good'];if(item.state==='can_add')return ['Hozzáadható','warn'];if(item.state==='related_unlinked')return ['Kapcsolódó, nincs összekötve','warn'];if(item.state==='uncertain_order')return ['Bizonytalan rendelés','warn'];return ['Kihagyva / nem vásárlás','bad']}
function eventLabel(value:string|null){const labels:Record<string,string>={order_created:'Rendelés',order_updated:'Rendelés frissítés',payment_completed:'Fizetés',shipment:'Feladás / szállítás',delivery:'Kézbesítés',invoice_or_receipt:'Számla / nyugta',refund:'Visszatérítés',return:'Visszaküldés',other:'Egyéb'};return value?labels[value]||value:'Nem értelmezett'}

function cardHtml(item:ScanItem){const [state,cls]=stateLabel(item);const money=formatMoney(item.total,item.currency);return `<article class="scan-email-card" data-source-id="${escapeHtml(item.id)}"><div class="scan-email-top"><strong>${escapeHtml(item.subject)}</strong><span class="scan-email-date">${escapeHtml(formatDate(item.receivedAt))}</span></div><div class="scan-email-meta"><span class="scan-chip ${cls}">${escapeHtml(state)}</span><span class="scan-chip">${escapeHtml(eventLabel(item.eventType))}</span>${item.validationStatus?`<span class="scan-chip">${escapeHtml(item.validationStatus)}</span>`:''}</div><div class="scan-email-details">${item.merchant?`<div><strong>Webshop:</strong> ${escapeHtml(item.merchant)}</div>`:''}${item.orderNumber?`<div><strong>Rendelés:</strong> ${escapeHtml(item.orderNumber)}</div>`:''}${money?`<div><strong>Összeg:</strong> ${escapeHtml(money)}</div>`:''}${item.productCount?`<div><strong>Termék:</strong> ${item.productCount} db</div>`:''}${item.senderDomain?`<div><strong>Feladó domain:</strong> ${escapeHtml(item.senderDomain)}</div>`:''}${item.state==='not_purchase'&&item.processingStatus==='ignored'?'<div><strong>Mi történt?</strong> A BuyFlow előszűrője ezt nem küldte tovább AI-elemzésre.</div>':''}${item.linkedPurchase?`<div><strong>Kapcsolva:</strong> ${escapeHtml(item.linkedPurchase.merchantName||'Vásárlás')} ${item.linkedPurchase.orderNumber?`#${escapeHtml(item.linkedPurchase.orderNumber)}`:''}</div>`:''}</div>${item.canAdd?'<button class="scan-add-button" type="button">Hozzáadás a BuyFlowhoz</button>':''}</article>`}

async function render(connectionId:string){const body=document.querySelector<HTMLElement>('#scan-review-body');if(!body)return;try{const data=await request<AuditResponse>(`/api/email-connections/${encodeURIComponent(connectionId)}/full-audit`);const audit=data.audit;const working=audit&&['pending','processing','retry'].includes(audit.status);body.innerHTML=`<div class="scan-review-note"><strong>Teljes 7 napos teszt.</strong> Ez nem használ <code>category:purchases</code> korlátozást. Az elmúlt 7 nap Gmail-leveleit nézzük, így azt is látod, mit hagy ki a jelenlegi BuyFlow előszűrő.</div>${working?'<div class="scan-review-status"><strong>Ellenőrzés folyamatban…</strong><span>Az eredménylista közben folyamatosan bővül.</span></div>':''}<div class="scan-review-summary"><div class="scan-review-stat"><strong>${data.summary.totalVisible}</strong><span>látott email</span></div><div class="scan-review-stat"><strong>${data.summary.inBuyFlow}</strong><span>BuyFlowban</span></div><div class="scan-review-stat"><strong>${data.summary.canAdd}</strong><span>hozzáadható</span></div><div class="scan-review-stat"><strong>${data.summary.relatedUnlinked}</strong><span>kapcsolódó</span></div><div class="scan-review-stat"><strong>${data.summary.uncertain}</strong><span>bizonytalan</span></div><div class="scan-review-stat"><strong>${data.summary.notPurchase}</strong><span>kihagyott</span></div></div><button id="scan-review-refresh" class="scan-review-refresh" type="button">Eredmények frissítése</button><div class="scan-review-list">${data.items.length?data.items.map(cardHtml).join(''):'<div class="scan-review-empty">Még nincs 7 napos eredmény.</div>'}</div>`;
body.querySelector<HTMLButtonElement>('#scan-review-refresh')?.addEventListener('click',()=>void render(connectionId));
body.querySelectorAll<HTMLButtonElement>('.scan-add-button').forEach(button=>{button.addEventListener('click',()=>void(async()=>{const card=button.closest<HTMLElement>('[data-source-id]');const sourceId=card?.dataset.sourceId;if(!sourceId)return;button.disabled=true;button.textContent='Hozzáadás…';try{await request(`/api/email-connections/${encodeURIComponent(connectionId)}/full-audit/${encodeURIComponent(sourceId)}/add-purchase`,{method:'POST'});button.textContent='Hozzáadva ✓';await render(connectionId);window.setTimeout(()=>window.location.reload(),600)}catch{button.disabled=false;button.textContent='Nem sikerült – próbáld újra'}})())});
if(working)window.setTimeout(()=>void render(connectionId),3000);
}catch{body.innerHTML='<div class="scan-review-error">Az eredmények most nem tölthetők be. Próbáld újra.</div>'}}

async function openReview(connectionId:string){close();const overlay=document.createElement('div');overlay.id='buyflow-scan-review-overlay';overlay.className='scan-review-overlay';overlay.innerHTML=`<div class="scan-review-backdrop" data-scan-close></div><section class="scan-review-sheet" role="dialog" aria-modal="true"><header class="scan-review-header"><div><p>BUYFLOW TESZT</p><h2>7 napos AI ellenőrzés</h2></div><button class="scan-review-close" type="button" data-scan-close>×</button></header><div id="scan-review-body"><div class="scan-review-status"><strong>Betöltés…</strong></div></div></section>`;overlay.querySelectorAll('[data-scan-close]').forEach(el=>el.addEventListener('click',close));document.body.appendChild(overlay);await render(connectionId)}

async function startAudit(connectionId:string,button:HTMLButtonElement){button.disabled=true;button.textContent='7 nap ellenőrzése indul…';try{await request(`/api/email-connections/${encodeURIComponent(connectionId)}/full-audit`,{method:'POST'});await openReview(connectionId)}catch{window.alert('Most nem sikerült elindítani a teljes 7 napos ellenőrzést.')}finally{button.disabled=false;button.textContent='Teljes 7 napos ellenőrzés indítása'}}

async function enhanceSettings(){const container=document.querySelector<HTMLElement>('#gmail-connection-content.connected');if(!container||container.dataset.scanReviewEnhanced==='1')return;container.dataset.scanReviewEnhanced='1';try{const connection=await activeConnection();if(!connection)return;const actions=document.createElement('div');actions.className='scan-review-actions';actions.innerHTML='<button id="start-full-seven-day-audit" class="scan-review-button primary" type="button">Teljes 7 napos ellenőrzés indítása</button><button id="view-full-seven-day-audit" class="scan-review-button secondary" type="button">7 nap eredményeinek megtekintése</button>';container.appendChild(actions);actions.querySelector<HTMLButtonElement>('#start-full-seven-day-audit')?.addEventListener('click',event=>void startAudit(connection.id,event.currentTarget as HTMLButtonElement));actions.querySelector<HTMLButtonElement>('#view-full-seven-day-audit')?.addEventListener('click',()=>void openReview(connection.id))}catch{container.dataset.scanReviewEnhanced='0'}}

const observer=new MutationObserver(()=>void enhanceSettings());observer.observe(document.documentElement,{childList:true,subtree:true});void enhanceSettings();
document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});
