import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';
import {getSupabaseAdmin} from '../db/supabase-admin.js'; import {createEmailProvider} from '../email/factory.js'; import type {NormalizedEmail} from '../email/types.js';
import {planNormalizedInboundEmail} from '../pipeline/normalized-inbound-pipeline.js'; import {resolveAuthenticatedApiUser} from './auth.js';
import {BLIND_V2_COMMERCE,BLIND_V2_NOISE} from './field-blind-holdout-v2-truth.js'; import type {GroundTruthExpectation} from './field-ground-truth-v1.js';
const F=['eventType','merchant','orderNumber','total','currency','carrier','trackingNumber','paymentStatus','products'] as const; type FN=typeof F[number];
const ids=new Set([...BLIND_V2_COMMERCE.map(x=>x.messageId),...BLIND_V2_NOISE]); const norm=(v:unknown)=>typeof v==='string'?v.normalize('NFKC').trim().toLowerCase():v;
const same=(a:unknown,b:unknown)=>JSON.stringify(norm(a))===JSON.stringify(norm(b));
function actual(p:ReturnType<typeof planNormalizedInboundEmail>){const r=p.validatedResult??p.structuredResult;return {eventType:r.event_type??p.classification??null,merchant:r.merchant??r.merchant_legal_name??null,orderNumber:r.order_number??null,total:r.total??null,currency:r.currency??null,carrier:r.carrier??null,trackingNumber:r.tracking_number??null,paymentStatus:r.payment_status??null,products:Array.isArray(r.products)?r.products:[]} as Record<FN,unknown>}
function ev(e:GroundTruthExpectation<unknown>,a:unknown){if(e.state==='not_asserted')return{asserted:false,pass:true};if(e.state==='null')return{asserted:true,pass:a==null||(Array.isArray(a)&&a.length===0)};return{asserted:true,pass:same(e.value,a)}}
async function user(req:FastifyRequest,rep:FastifyReply){const u=await resolveAuthenticatedApiUser(req.headers.authorization);if(!u){await rep.code(401).send({error:'unauthorized'});return null}return u}
async function run(uid:string){const db=getSupabaseAdmin() as any;const {data:c}=await db.from('email_connections').select('provider_account_id').eq('user_id',uid).eq('provider','nylas').eq('status','active').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!c?.provider_account_id)throw new Error('active_nylas_connection_not_found');const p=createEmailProvider({provider:'nylas',providerAccountId:c.provider_account_id});let cursor:string|undefined,scanned=0;const found=new Map<string,NormalizedEmail>();do{const page=await p.searchMessages({query:'-in:spam -in:trash',limit:100,...(cursor?{cursor}:{})});for(const m of page.messages)if(ids.has(m.providerMessageId))found.set(m.providerMessageId,m);scanned+=page.messages.length;cursor=page.nextCursor}while(cursor&&scanned<4000&&found.size<ids.size);
let tp=0,fn=0,fp=0,tn=0,asserted=0,passed=0,critical=0;const summary=Object.fromEntries(F.map(x=>[x,{asserted:0,passed:0,failed:0,accuracy:null as number|null}]));const rows:any[]=[];
for(const t of BLIND_V2_COMMERCE){const m=found.get(t.messageId);if(!m){fn++;rows.push({messageId:t.messageId,found:false,truth:'commerce'});continue}const plan=planNormalizedInboundEmail({email:m});const detected=!!plan.classification&&plan.classification!=='other';if(detected)tp++;else fn++;const a=actual(plan);let crit=false;const fs=F.map(n=>{const x=ev(t[n] as GroundTruthExpectation<unknown>,a[n]);if(x.asserted){asserted++;(summary[n] as any).asserted++;if(x.pass){passed++;(summary[n] as any).passed++}else{(summary[n] as any).failed++;if(['eventType','orderNumber','total','currency','carrier','trackingNumber','paymentStatus'].includes(n))crit=true}}return{name:n,...x,actual:a[n]}});if(crit)critical++;rows.push({messageId:t.messageId,found:true,truth:'commerce',detected,classification:plan.classification,parserVersion:plan.parserVersion,criticalMismatch:crit,fields:fs})}
for(const id of BLIND_V2_NOISE){const m=found.get(id);if(!m){rows.push({messageId:id,found:false,truth:'noise'});continue}const plan=planNormalizedInboundEmail({email:m});const detected=!!plan.classification&&plan.classification!=='other';if(detected)fp++;else tn++;rows.push({messageId:id,found:true,truth:'noise',detected,classification:plan.classification,parserVersion:plan.parserVersion})}
for(const n of F){const s=summary[n] as any;s.accuracy=s.asserted?s.passed/s.asserted:null}return{ok:true,mode:'shadow',productionWrites:0,aiCalls:0,frozenBeforeRun:true,expectedMessages:ids.size,foundMessages:found.size,scanned,detection:{tp,fn,fp,tn,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null},fields:{asserted,passed,accuracy:asserted?passed/asserted:null,criticalMismatchCount:critical,summary},rows}}
function html(){return `<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Blind Field Holdout v2</title><style>body{font-family:system-ui;background:#071020;color:#fff;max-width:1000px;margin:auto;padding:28px}.c{background:#0d1830;padding:20px;border-radius:18px;margin:14px}button{padding:12px;border:0;border-radius:10px;background:#7c4dff;color:white;font-weight:700}</style><div class=c><b>BLIND FIELD HOLDOUT v2 · FROZEN BEFORE RUN · 0 WRITE · 0 AI</b><h1>Field Blind Holdout v2</h1><button id=b>Első vakteszt futtatása</button><span id=s></span></div><div class=c id=o></div><script type=module>import{createClient}from'https://esm.sh/@supabase/supabase-js@2';const c=createClient('https://acjenqkrvnkdvvgordry.supabase.co','sb_publishable_aFkSa0y3YHzgBAxRx3nwxg_o5_8shFp');b.onclick=async()=>{const{x,data}=await c.auth.getSession();if(!data.session){s.textContent=' Jelentkezz be.';return}s.textContent=' Fut…';const r=await fetch('/api/audit/field-blind-v2',{method:'POST',headers:{Authorization:'Bearer '+data.session.access_token}}),d=await r.json(),p=v=>v==null?'—':(v*100).toFixed(1)+'%';o.innerHTML='<h2>Detection: '+p(d.detection.precision)+' precision · '+p(d.detection.recall)+' recall</h2><p>TP '+d.detection.tp+' · FN '+d.detection.fn+' · FP '+d.detection.fp+' · TN '+d.detection.tn+'</p><h2>Fields: '+p(d.fields.accuracy)+'</h2><p>Found '+d.foundMessages+'/'+d.expectedMessages+' · asserted '+d.fields.asserted+' · critical mismatch '+d.fields.criticalMismatchCount+'</p>'+Object.entries(d.fields.summary).map(([k,v])=>'<p>'+k+' · '+p(v.accuracy)+' · '+v.passed+'/'+v.asserted+'</p>').join('');s.textContent=' Kész. 0 write · 0 AI.'}</script>`}
export async function registerFieldBlindHoldoutV2(app:FastifyInstance){app.get('/audit-fields-blind-v2',async(_q,r)=>r.type('text/html; charset=utf-8').header('Cache-Control','no-store').send(html()));app.post('/api/audit/field-blind-v2',async(q,r)=>{const u=await user(q,r);if(!u)return;try{return r.send(await run(u.id))}catch(e){return r.code(503).send({ok:false,error:e instanceof Error?e.message:'blind_v2_failed'})}})}
