import type { ProtocolProfile } from '../types.js';

/**
 * Alza Hungary merchant shadow profile.
 *
 * V1 is based on multiple directly observed recipient-email lifecycles from
 * segito@alza.hu. Merchant logistics evidence remains lower authority than
 * direct carrier evidence, and return/refund stages are kept deliberately
 * separate.
 */
export const ALZA_MERCHANT_TEST_V1: ProtocolProfile = {
  protocol_id: 'merchant.hu.alza',
  protocol_version: '1.0.0-test.1',
  kind: 'merchant',
  status: 'test',
  display_name: 'Alza Hungary',
  country: 'HU',
  sender_domains: ['alza.hu'],
  sender_addresses: ['segito@alza.hu'],
  identifier_patterns: {
    order_id: [
      'Megrendel[eé]s\\s+(\\d{9})',
      'objednavka-(\\d{9})',
      'order-details-(\\d{9})',
    ],
    tracking_id: ['parcelNumber=(\\d{14})'],
    invoice_id: [],
    payment_reference: [],
  },
  sources: [
    {
      id: 'alza-observed-order-created',
      title: 'Observed Alza order-received email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email from segito@alza.hu says the identified order was received and explicitly says the message itself has not yet formed a contract.',
    },
    {
      id: 'alza-observed-processing',
      title: 'Observed Alza processing email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email says processing of the identified order has started and asks the customer to wait for the next SMS/email. This is not carrier possession.',
    },
    {
      id: 'alza-observed-payment-action',
      title: 'Observed Alza bank-transfer payment-required email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email says only payment remains, asks for a concrete HUF amount and bank transfer, and provides the order reference. This is PAYMENT_ACTION_REQUIRED, not payment failure.',
    },
    {
      id: 'alza-observed-cancelled-unpaid',
      title: 'Observed Alza unpaid-order cancellation email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email explicitly states the identified order was cancelled because it was not paid. Cancellation does not prove a failed payment transaction.',
    },
    {
      id: 'alza-observed-shipped-dpd',
      title: 'Observed Alza DPD handoff email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email explicitly says the order was handed to the carrier, identifies DPD, gives a 14-digit DPD parcel number in the tracking URL, and says the carrier will provide exact delivery timing.',
    },
    {
      id: 'alza-observed-delayed',
      title: 'Observed Alza delayed-delivery email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email explicitly apologizes for a delay and gives a new expected delivery time. V1 maps this to DELAYED only.',
    },
    {
      id: 'alza-observed-ready-alzabox',
      title: 'Observed AlzaBox ready-for-pickup email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email says the identified order has arrived in a named AlzaBox, supplies pickup code and deadline, and can still show an unpaid amount. Arrival in the box is READY_FOR_PICKUP, not DELIVERED or PAYMENT_SUCCESS.',
    },
    {
      id: 'alza-observed-invoice-link',
      title: 'Observed Alza final invoice-download evidence (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Carrier-handoff and AlzaBox-ready emails contain an explicit Számla letöltése link plus wording that Alza accepted the order and the contract was formed. An earlier processing email can already display a same-looking invoice link while explicitly saying no contract exists, so V1 requires the later contract-formation wording too.',
    },
    {
      id: 'alza-observed-return-request',
      title: 'Observed Alza return/withdrawal request intake email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email assigns an AVRA case number and instructs the customer to send the product. This proves a return request only; the product has not yet been received by Alza.',
    },
    {
      id: 'alza-observed-return-received',
      title: 'Observed Alza physical return receipt email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email explicitly says the product was received for case processing and identifies the case type as withdrawal (Elállás). V1 maps this physical receipt to RETURN.',
    },
    {
      id: 'alza-observed-refund',
      title: 'Observed Alza card refund-issued email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct email explicitly says a concrete HUF amount was refunded and sent back to the bank card, with bank credit expected within up to three business days. The same message links the withdrawal case and related order.',
    },
    {
      id: 'alza-observed-auth',
      title: 'Observed Alza authenticated mail infrastructure (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Representative order and refund raw MIME both verify DKIM pass for alza.hu, SPF pass for segito@alza.hu, DMARC pass, direct segito@alza.hu Return-Path and smtpout*.alza.cz transport. V1 treats exact alza.hu DKIM as authority; transport is not identity.',
    },
    {
      id: 'alza-observed-same-channel-marketing',
      title: 'Observed AlzaPlus marketing email on same authenticated sender (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'The exact same segito@alza.hu + alza.hu DKIM channel also sends AlzaPlus promotional mail. Sender identity alone is therefore not lifecycle evidence.',
    },
    {
      id: 'alza-official-buying-guide',
      title: 'Alza - Hogyan vásárolj',
      url: 'https://www.alza.hu/hogyan-vasarolj',
      provenance: 'official_documentation',
      notes: 'Alza states it continuously informs customers about order status and separately documents order cancellation and claims/returns.',
    },
    {
      id: 'alza-official-alzabox',
      title: 'AlzaBox - gyorsan átvehető megrendelés',
      url: 'https://www.alza.hu/alzabox',
      provenance: 'official_documentation',
      notes: 'Alza documents AlzaBox pickup, pickup-code flow, optional payment at the box, and separate use of AlzaBox for return/claim submission.',
    },
    {
      id: 'alza-official-payment-refund',
      title: 'Alza - Fizetési módok',
      url: 'https://www.alza.hu/fizetesi-modok-art14905.htm',
      provenance: 'official_documentation',
      notes: 'Alza documents payment methods and states refunds are generally returned through the same payment method, including card refunds to the card-linked account.',
    },
    {
      id: 'alza-official-returns',
      title: 'Alza - Termékek visszaküldése és szerződéstől történő elállás',
      url: 'https://www.alza.hu/szerviz-szolgaltatasainkhogy-semmire-zakuldesenek-menete-art12601.htm',
      provenance: 'official_documentation',
      notes: 'Alza separates withdrawal/return initiation, receipt of returned goods and later refund timing. V1 mirrors those boundaries.',
    },
    {
      id: 'alza-official-account-documents',
      title: 'Alza - Kapcsolat / orders and payments',
      url: 'https://m.alza.hu/kapcsolat',
      provenance: 'official_documentation',
      notes: 'Alza states electronic invoices/documents are available in the customer account and that refund notifications are sent by email.',
    },
  ],
  events: [
    {
      event: 'ORDER_CREATED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.order-created.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-order-created'] },
        { id: 'alza.order-created.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.order-created.subject', field: 'subject', pattern: '^K[oö]sz[oö]nj[uü]k\\s+\\d{9}\\s+sz\\.\\s+megrendel[eé]sed$', required: true, source_ids: ['alza-observed-order-created'] },
        { id: 'alza.order-created.received', field: 'body', pattern: 'Megrendel[eé]sed\\s+rendben\\s+megkaptuk', required: true, source_ids: ['alza-observed-order-created'] },
        { id: 'alza.order-created.no-contract-yet', field: 'body', pattern: 'm[eé]g\\s+nem\\s+j[oö]tt\\s+l[eé]tre\\s+szerz[oő]d[eé]s', required: true, source_ids: ['alza-observed-order-created'] },
      ],
    },
    {
      event: 'ORDER_PROCESSING',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.processing.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-processing'] },
        { id: 'alza.processing.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.processing.subject', field: 'subject', pattern: '^M[aá]r\\s+dolgozunk\\s+rajta\\.\\s*/\\s*\\d{9}\\s+sz\\.\\s+megr\\.$', required: true, source_ids: ['alza-observed-processing'] },
        { id: 'alza.processing.body', field: 'body', pattern: 'megrendel[eé]sed\\s+feldolgoz[aá]s[aá]t\\s+megkezdt[uü]k', required: true, source_ids: ['alza-observed-processing'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_SET_SHIPPED_AT', 'DO_NOT_MARK_IN_TRANSIT', 'DO_NOT_MARK_DELIVERED'],
    },
    {
      event: 'PAYMENT_ACTION_REQUIRED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.payment-action.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-payment-action'] },
        { id: 'alza.payment-action.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.payment-action.subject', field: 'subject', pattern: '^K[oö]sz[oö]nj[uü]k\\s+a\\s+megrendel[eé]st,\\s+m[aá]r\\s+csak\\s+a\\s+fizet[eé]s\\s+van\\s+h[aá]tra\\s*/\\s*\\d{9}\\s+sz\\.\\s+megr\\.$', required: true, source_ids: ['alza-observed-payment-action'] },
        { id: 'alza.payment-action.amount', field: 'body', pattern: 'K[eé]rj[uü]k,\\s+fizess\\s+[\\d\\s]+(?:,\\d{2})?\\s*HUF\\s+[oö]sszeget', required: true, source_ids: ['alza-observed-payment-action'] },
        { id: 'alza.payment-action-transfer', field: 'body', pattern: 'K[eé]rj[uü]k,\\s+utald\\s+el\\s+az\\s+[oö]sszeget', required: true, source_ids: ['alza-observed-payment-action'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_REFUNDED'],
    },
    {
      event: 'CANCELLED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.cancelled.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-cancelled-unpaid'] },
        { id: 'alza.cancelled.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.cancelled.subject', field: 'subject', pattern: '^Inform[aá]ci[oó]\\s+a\\(z\\)\\s+\\d{9}\\s+sz\\.\\s+megrendel[eé]sr[oő]l$', required: true, source_ids: ['alza-observed-cancelled-unpaid'] },
        { id: 'alza.cancelled.explicit', field: 'body', pattern: 'A\\s+megrendel[eé]s\\s+t[oö]r[oö]lve', required: true, source_ids: ['alza-observed-cancelled-unpaid'] },
        { id: 'alza.cancelled.unpaid', field: 'body', pattern: 'mivel\\s+nem\\s+lett\\s+kifizetve', required: true, source_ids: ['alza-observed-cancelled-unpaid'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_DELIVERED', 'DO_NOT_MARK_REFUNDED'],
    },
    {
      event: 'SHIPPED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.shipped.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-shipped-dpd'] },
        { id: 'alza.shipped.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.shipped.subject', field: 'subject', pattern: '^\\d{9}\\s+sz\\.\\s+megrendel[eé]sed\\s+[eé]pp\\s+most\\s+k[uü]ldt[uü]k\\s+el\\.$', required: true, source_ids: ['alza-observed-shipped-dpd'] },
        { id: 'alza.shipped.handoff', field: 'body', pattern: 'Megrendel[eé]sed\\s+[aá]tadtuk\\s+a\\s+sz[aá]ll[ií]t[oó]nak', required: true, source_ids: ['alza-observed-shipped-dpd'] },
        { id: 'alza.shipped.carrier', field: 'body', pattern: 'Sz[aá]ll[ií]t[oó][\\s\\S]{0,30}DPD', required: true, source_ids: ['alza-observed-shipped-dpd'] },
        { id: 'alza.shipped.tracking', field: 'body', pattern: 'parcelNumber=\\d{14}', required: true, source_ids: ['alza-observed-shipped-dpd'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_DELIVERED'],
    },
    {
      event: 'DELAYED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.delayed.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-delayed'] },
        { id: 'alza.delayed.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.delayed.subject', field: 'subject', pattern: '^\\d{9}\\s+sz\\.\\s+megrendel[eé]sed\\s+k[eé]sve\\s+[eé]rkezik$', required: true, source_ids: ['alza-observed-delayed'] },
        { id: 'alza.delayed.apology', field: 'body', pattern: 'Eln[eé]z[eé]st\\s+k[eé]r[uü]nk\\s+a\\s+k[eé]s[eé]s[eé]rt', required: true, source_ids: ['alza-observed-delayed'] },
        { id: 'alza.delayed.new-eta', field: 'body', pattern: 'k[eé]zbes[ií]t[eé]s\\s+v[aá]rhat[oó]\\s+[uú]j\\s+id[oő]pontja', required: true, source_ids: ['alza-observed-delayed'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_DELIVERED'],
    },
    {
      event: 'READY_FOR_PICKUP',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.ready.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-ready-alzabox'] },
        { id: 'alza.ready.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.ready.subject', field: 'subject', pattern: '^Vedd\\s+[aá]t\\s+\\d{9}\\s+sz\\.\\s+megrendel[eé]sed$', required: true, source_ids: ['alza-observed-ready-alzabox'] },
        { id: 'alza.ready.alzabox', field: 'body', pattern: 'Vedd\\s+[aá]t\\s+a\\s+megrendel[eé]sed\\s+az\\s+AlzaBoxb[oó]l', required: true, source_ids: ['alza-observed-ready-alzabox', 'alza-official-alzabox'] },
        { id: 'alza.ready.arrived', field: 'body', pattern: 'megrendel[eé]sed\\s+meg[eé]rkezett[\\s\\S]{0,180}AlzaBox', required: true, source_ids: ['alza-observed-ready-alzabox'] },
        { id: 'alza.ready.code', field: 'body', pattern: 'K[oó]d\\s+az\\s+[aá]tv[eé]telhez', required: true, source_ids: ['alza-observed-ready-alzabox'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_DELIVERED'],
    },
    {
      event: 'INVOICE',
      base_confidence: 0.99,
      positive_rules: [
        { id: 'alza.invoice.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-invoice-link'] },
        { id: 'alza.invoice.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.invoice.download-label', field: 'body', pattern: 'Sz[aá]mla\\s+let[oö]lt[eé]se', required: true, source_ids: ['alza-observed-invoice-link', 'alza-official-account-documents'] },
        { id: 'alza.invoice.pdf-link', field: 'body', pattern: 'alza\\.hu/Apps/pdfdoc\\.asp\\?d=AHUW\\d+', required: true, source_ids: ['alza-observed-invoice-link'] },
        { id: 'alza.invoice.contract-formed', field: 'body', pattern: 'Alza\\s+ezzel\\s+az\\s+[uü]zenettel\\s+elfogadta\\s+a\\s+megrendel[eé]sed[\\s\\S]{0,180}szerz[oő]d[eé]s\\s+j[oö]tt\\s+l[eé]tre', required: true, source_ids: ['alza-observed-invoice-link'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE'],
    },
    {
      event: 'OTHER',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.return-request.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-return-request'] },
        { id: 'alza.return-request.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.return-request.subject', field: 'subject', pattern: '^Az\\s+AVRA\\d+\\s+sz\\.\\s+reklam[aá]ci[oó]t\\s+befogadtuk$', required: true, source_ids: ['alza-observed-return-request'] },
        { id: 'alza.return-request.send-item', field: 'body', pattern: 'K[uü]ldd\\s+el\\s+nek[uü]nk\\s+a\\s+term[eé]ket', required: true, source_ids: ['alza-observed-return-request', 'alza-official-returns'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_AUTO_LINK', 'DO_NOT_MARK_DELIVERED', 'DO_NOT_MARK_REFUNDED'],
    },
    {
      event: 'RETURN',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.return.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-return-received'] },
        { id: 'alza.return.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.return.subject', field: 'subject', pattern: '^Vonatkoz[oó]\\s+inform[aá]ci[oó]k:\\s+AVRA\\d+$', required: true, source_ids: ['alza-observed-return-received'] },
        { id: 'alza.return.received', field: 'body', pattern: 'A\\s+term[eé]ket\\s+reklam[aá]ci[oó]ra\\s+[aá]tvett[uü]k', required: true, source_ids: ['alza-observed-return-received'] },
        { id: 'alza.return.withdrawal', field: 'body', pattern: 'Az\\s+eset\\s+t[ií]pusa:[\\s\\S]{0,80}El[aá]ll[aá]s', required: true, source_ids: ['alza-observed-return-received'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_AUTO_LINK', 'DO_NOT_MARK_REFUNDED'],
    },
    {
      event: 'REFUNDED',
      base_confidence: 1,
      positive_rules: [
        { id: 'alza.refund.sender', field: 'sender_address', pattern: '^segito@alza\\.hu$', required: true, source_ids: ['alza-observed-refund'] },
        { id: 'alza.refund.dkim', field: 'dkim_domain', pattern: '^alza\\.hu$', required: true, source_ids: ['alza-observed-auth'] },
        { id: 'alza.refund.subject', field: 'subject', pattern: '^P[eé]nzt\\s+k[uü]ld[uü]nk\\s+vissza\\s+sz[aá]modra\\.$', required: true, source_ids: ['alza-observed-refund'] },
        { id: 'alza.refund.explicit', field: 'body', pattern: 'Visszat[eé]r[ií]tett[uü]nk\\s+[\\d\\s]+\\s*Ft-ot', required: true, source_ids: ['alza-observed-refund'] },
        { id: 'alza.refund.card-sent', field: 'body', pattern: 'bankk[aá]rty[aá]dra\\s+visszautaltunk\\s+[\\d\\s]+\\s*Ft-ot', required: true, source_ids: ['alza-observed-refund', 'alza-official-payment-refund'] },
        { id: 'alza.refund.withdrawal-case', field: 'body', pattern: 'Az\\s+ok\\s+a\\s+v[aá]s[aá]rl[aá]st[oó]l\\s+val[oó]\\s+el[aá]ll[aá]s[\\s\\S]{0,100}AVRA\\d+', required: true, source_ids: ['alza-observed-refund'] },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE'],
    },
  ],
  notes: [
    'The initial thank-you email is ORDER_CREATED even though it explicitly says the legal contract has not yet formed. BuyFlow must not conflate order receipt with contract acceptance.',
    'ORDER_PROCESSING is not SHIPPED. The processing email asks the customer to wait for the next SMS/email and may already contain a same-looking invoice-download link.',
    'A Számla letöltése link alone is not enough for INVOICE in V1. The observed processing email contains that link while saying no contract exists, so the invoice rule also requires later explicit order acceptance / contract formation wording.',
    'The observed DPD SHIPPED rule requires explicit carrier handoff plus DPD identity and a 14-digit DPD tracking number. Direct DPD evidence remains higher authority for later physical logistics.',
    'DELAYED is independent from DELIVERY_FAILED. A revised ETA and apology do not prove a failed delivery attempt.',
    'AlzaBox arrival is READY_FOR_PICKUP, not DELIVERED. The ready email can still request payment, so it is also not PAYMENT_SUCCESS.',
    'The unpaid-order cancellation template maps to CANCELLED only. Not being paid is not proof that a card or bank transaction failed.',
    'The return-request email that says Küldd el nekünk a terméket is OTHER: it proves intent/instructions, not physical RETURN.',
    'RETURN requires explicit physical receipt of the product and case type Elállás. Because the observed return-received email exposes only an AVRA claim identifier and the current protocol schema has no claim_id field, V1 forbids auto-linking that event.',
    'REFUNDED requires explicit Visszatérítettünk plus bankkártyádra visszautaltunk wording. This is stronger than generic refund eligibility, intent or processing text.',
    'The same authenticated segito@alza.hu channel also carries AlzaPlus marketing, so sender and DKIM are necessary but never sufficient.',
    'No positive PAYMENT_SUCCESS, PAYMENT_FAILED, IN_TRANSIT, OUT_FOR_DELIVERY, DELIVERED, DELIVERY_FAILED or WARRANTY rule is implemented in V1 without a verified direct recipient template.',
  ],
};
