import type { ProtocolProfile } from '../types.js';

/**
 * GymBeam Hungary merchant shadow profile.
 *
 * This profile formalizes recipient-email families repeatedly observed in the
 * connected mailbox. It intentionally preserves merchant-vs-provider authority:
 * direct carrier evidence outranks GymBeam logistics wording and direct payment
 * provider evidence outranks merchant payment wording.
 */
export const GYMBEAM_MERCHANT_TEST_V1: ProtocolProfile = {
  protocol_id: 'merchant.hu.gymbeam',
  protocol_version: '1.0.0-test.1',
  kind: 'merchant',
  status: 'test',
  display_name: 'GymBeam Hungary',
  country: 'HU',
  sender_domains: ['gymbeam.hu'],
  sender_addresses: ['info@rendeles.gymbeam.hu', 'info@service.gymbeam.hu'],
  identifier_patterns: {
    order_id: [
      '(?:a\\(z\\)|a|az)?\\s*(\\d{10})\\s+sz[aá]m[uú]\\s+rendel[eé]s',
      'a\\(z\\)\\s+(\\d{10})\\s+rendel[eé]s',
    ],
    tracking_id: [
      'a\\s+(\\d{20,30})\\s+sz[aá]mmal\\s+k[oö]vetheted\\s+a\\s+csomagot',
    ],
    invoice_id: [
      '(?:az|a)\\s+(\\d{10,12})\\s+sz[aá]m[uú]\\s+(?:elektronikus\\s+)?sz[aá]ml',
    ],
    payment_reference: [],
  },
  sources: [
    {
      id: 'gymbeam-observed-legacy-order-created',
      title: 'Observed GymBeam legacy order-recorded email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct recipient email from info@rendeles.gymbeam.hu explicitly said the 10-digit order was successfully recorded and processing would begin soon. It also contained order summary, payment and shipping method.',
    },
    {
      id: 'gymbeam-observed-legacy-auth',
      title: 'Observed GymBeam legacy authenticated mail channel (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Raw MIME verified DKIM pass for rendeles.gymbeam.hu, SPF pass, DMARC pass and service.gymbeam.com return-path/transport infrastructure.',
    },
    {
      id: 'gymbeam-observed-processing',
      title: 'Observed GymBeam current order-processing email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct info@service.gymbeam.hu recipient email used the subject that the order is being processed, said the order was received and is already being prepared, and contained a full order summary.',
    },
    {
      id: 'gymbeam-observed-service-auth',
      title: 'Observed GymBeam current authenticated service channel (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Representative current lifecycle/invoice raw MIME verified DKIM pass for service.gymbeam.hu, SPF pass and DMARC pass for GymBeam.',
    },
    {
      id: 'gymbeam-observed-prehandoff',
      title: 'Observed GymBeam packed / future carrier handoff email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Subject says the order is on the way and top copy says sent, but the body explicitly says it was packed and will soon get into the hands of Express One. This proves pre-handoff, not physical shipment.',
    },
    {
      id: 'gymbeam-observed-delay',
      title: 'Observed GymBeam delivery-delay email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct automated GymBeam email says the carrier delivery is taking longer than usual and GymBeam is coordinating with the courier.',
    },
    {
      id: 'gymbeam-observed-current-invoice',
      title: 'Observed GymBeam current invoice-ready email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct current service email explicitly identifies both the order and invoice, says the invoice is ready and exposes a GymBeam invoice-view link. No attachment is required.',
    },
    {
      id: 'gymbeam-observed-legacy-paid-invoice',
      title: 'Observed GymBeam legacy paid-order invoice email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Direct legacy recipient email explicitly says GymBeam received the amount due for the identified order, says the order is already paid, and provides the identified electronic invoice.',
    },
    {
      id: 'gymbeam-official-delivery',
      title: 'GymBeam Hungary - Kiszállítás és visszaküldés',
      url: 'https://gymbeam.hu/content/kezbesites',
      provenance: 'official_documentation',
      notes: 'Current GymBeam documentation lists Express One, GLS, Foxpost, Wolt Drive and pickup options and distinguishes merchant preparation from carrier delivery.',
    },
    {
      id: 'gymbeam-official-faq',
      title: 'GymBeam Hungary - Gyakran ismételt kérdések',
      url: 'https://gymbeam.hu/content/gyakran-ismetelt-kerdesek',
      provenance: 'official_documentation',
      notes: 'GymBeam states orders are assembled before carrier responsibility, sends separate delivery-timing email, contacts customers when delivery is delayed, and waits for bank-transfer receipt before processing.',
    },
    {
      id: 'gymbeam-official-returns',
      title: 'GymBeam Hungary - Visszaküldés',
      url: 'https://gymbeam.hu/visszakuldes',
      provenance: 'official_documentation',
      notes: 'Current return flow is available within 30 days from delivery and requires order identity plus email. No direct recipient return/refund template was observed in this mailbox round.',
    },
    {
      id: 'gymbeam-mailbox-missing-events',
      title: 'Targeted GymBeam cancellation/refund/failure/warranty searches (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Targeted mailbox searches found no sufficiently verified direct recipient template for cancellation, return, settled refund, failed payment or warranty lifecycle, so no positive rules are implemented for those events.',
    },
  ],
  events: [
    {
      event: 'ORDER_CREATED',
      base_confidence: 0.99,
      positive_rules: [
        {
          id: 'gymbeam.order-created.sender',
          field: 'sender_address',
          pattern: '^info@rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-order-created'],
        },
        {
          id: 'gymbeam.order-created.dkim',
          field: 'dkim_domain',
          pattern: '^rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-auth'],
        },
        {
          id: 'gymbeam.order-created.subject',
          field: 'subject',
          pattern: 'r[oö]gz[ií]tett[uü]k\\s+a\\s+\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sed',
          required: true,
          source_ids: ['gymbeam-observed-legacy-order-created'],
        },
        {
          id: 'gymbeam.order-created.recorded',
          field: 'body',
          pattern: 'rendszer[uü]nk\\s+sikeresen\\s+r[oö]gz[ií]tett',
          required: true,
          source_ids: ['gymbeam-observed-legacy-order-created'],
        },
        {
          id: 'gymbeam.order-created.future-processing',
          field: 'body',
          pattern: 'hamarosan\\s+megkezdj[uü]k\\s+a\\s+feldolgoz[aá]s[aá]t',
          required: true,
          source_ids: ['gymbeam-observed-legacy-order-created'],
        },
      ],
    },
    {
      event: 'ORDER_PROCESSING',
      base_confidence: 0.99,
      positive_rules: [
        {
          id: 'gymbeam.processing.sender',
          field: 'sender_address',
          pattern: '^info@service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-processing'],
        },
        {
          id: 'gymbeam.processing.dkim',
          field: 'dkim_domain',
          pattern: '^service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-service-auth'],
        },
        {
          id: 'gymbeam.processing.subject',
          field: 'subject',
          pattern: 'rendel[eé]sed\\s+feldolgoz[aá]s\\s+alatt\\s+van',
          required: true,
          source_ids: ['gymbeam-observed-processing'],
        },
        {
          id: 'gymbeam.processing.received',
          field: 'body',
          pattern: 'megkaptuk\\s+a\\s+rendel[eé]sedet',
          required: true,
          source_ids: ['gymbeam-observed-processing'],
        },
        {
          id: 'gymbeam.processing.preparing',
          field: 'body',
          pattern: '\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sed\\s+m[aá]r\\s+k[eé]sz[uü]l',
          required: true,
          source_ids: ['gymbeam-observed-processing'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE'],
    },
    {
      event: 'SHIPMENT_CREATED',
      base_confidence: 1,
      positive_rules: [
        {
          id: 'gymbeam.prehandoff.sender',
          field: 'sender_address',
          pattern: '^info@service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-prehandoff'],
        },
        {
          id: 'gymbeam.prehandoff.dkim',
          field: 'dkim_domain',
          pattern: '^service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-service-auth'],
        },
        {
          id: 'gymbeam.prehandoff.subject',
          field: 'subject',
          pattern: 'megrendel[eé]sed\\s+[uú]ton\\s+van',
          required: true,
          source_ids: ['gymbeam-observed-prehandoff'],
        },
        {
          id: 'gymbeam.prehandoff.packed',
          field: 'body',
          pattern: '\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sedet\\s+becsomagoltuk',
          required: true,
          source_ids: ['gymbeam-observed-prehandoff'],
        },
        {
          id: 'gymbeam.prehandoff.future-carrier',
          field: 'body',
          pattern: 'hamarosan\\s+(?:a\\s+)?[^\\r\\n]{0,80}sz[aá]ll[ií]t[oó]\\s+c[eé]g\\s+kez[eé]be\\s+ker[uü]l',
          required: true,
          source_ids: ['gymbeam-observed-prehandoff', 'gymbeam-official-faq'],
        },
        {
          id: 'gymbeam.prehandoff.tracking',
          field: 'body',
          pattern: '\\d{20,30}\\s+sz[aá]mmal\\s+k[oö]vetheted\\s+a\\s+csomagot',
          required: true,
          source_ids: ['gymbeam-observed-prehandoff'],
        },
      ],
      prohibitions: [
        'DO_NOT_CREATE_PURCHASE',
        'DO_NOT_SET_SHIPPED_AT',
        'DO_NOT_MARK_IN_TRANSIT',
        'DO_NOT_MARK_DELIVERED',
      ],
    },
    {
      event: 'DELAYED',
      base_confidence: 0.99,
      positive_rules: [
        {
          id: 'gymbeam.delay.sender',
          field: 'sender_address',
          pattern: '^info@service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-delay'],
        },
        {
          id: 'gymbeam.delay.dkim',
          field: 'dkim_domain',
          pattern: '^service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-service-auth'],
        },
        {
          id: 'gymbeam.delay.subject',
          field: 'subject',
          pattern: '^Ellen[oő]rizz[uü]k\\s+a\\s+k[eé]zbes[ií]t[eé]st$',
          required: true,
          source_ids: ['gymbeam-observed-delay'],
        },
        {
          id: 'gymbeam.delay.slower-than-usual',
          field: 'body',
          pattern: 'sz[aá]ll[ií]t[oó]c[eé]g\\s+[aá]ltali\\s+k[eé]zbes[ií]t[eé]se\\s+a\\s+szok[aá]sosn[aá]l\\s+kiss[eé]\\s+tov[aá]bb\\s+tart',
          required: true,
          source_ids: ['gymbeam-observed-delay', 'gymbeam-official-faq'],
        },
        {
          id: 'gymbeam.delay.courier-coordination',
          field: 'body',
          pattern: 'akt[ií]van\\s+egyeztet[uü]nk\\s+a\\s+fut[aá]rszolg[aá]lattal',
          required: true,
          source_ids: ['gymbeam-observed-delay'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_DELIVERED'],
    },
    {
      event: 'PAYMENT_SUCCESS',
      base_confidence: 0.99,
      positive_rules: [
        {
          id: 'gymbeam.payment-success.sender',
          field: 'sender_address',
          pattern: '^info@rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
        {
          id: 'gymbeam.payment-success.dkim',
          field: 'dkim_domain',
          pattern: '^rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-auth'],
        },
        {
          id: 'gymbeam.payment-success.received-amount',
          field: 'body',
          pattern: 'megkaptuk[\\s\\S]{0,100}\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sed[eé]rt\\s+fizetend[oő][\\s\\S]{0,40}[oö]sszeget',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
        {
          id: 'gymbeam.payment-success.already-paid',
          field: 'body',
          pattern: 'rendel[eé]s\\s+m[aá]r\\s+fizetett',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_MARK_REFUNDED'],
    },
    {
      event: 'INVOICE',
      base_confidence: 1,
      positive_rules: [
        {
          id: 'gymbeam.invoice-current.sender',
          field: 'sender_address',
          pattern: '^info@service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-current-invoice'],
        },
        {
          id: 'gymbeam.invoice-current.dkim',
          field: 'dkim_domain',
          pattern: '^service\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-service-auth'],
        },
        {
          id: 'gymbeam.invoice-current.subject',
          field: 'subject',
          pattern: 'sz[aá]ml[aá]d\\s+elk[eé]sz[uü]lt',
          required: true,
          source_ids: ['gymbeam-observed-current-invoice'],
        },
        {
          id: 'gymbeam.invoice-current.document',
          field: 'body',
          pattern: '\\d{10,12}\\s+sz[aá]m[uú]\\s+sz[aá]ml[aá]d\\s+elk[eé]sz[uü]lt',
          required: true,
          source_ids: ['gymbeam-observed-current-invoice'],
        },
        {
          id: 'gymbeam.invoice-current-purchase',
          field: 'body',
          pattern: 'v[aá]s[aá]rl[aá]sr[oó]l\\s+sz[oó]l[oó]\\s+sz[aá]mla',
          required: true,
          source_ids: ['gymbeam-observed-current-invoice'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE'],
    },
    {
      event: 'INVOICE',
      base_confidence: 1,
      positive_rules: [
        {
          id: 'gymbeam.invoice-legacy.sender',
          field: 'sender_address',
          pattern: '^info@rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
        {
          id: 'gymbeam.invoice-legacy.dkim',
          field: 'dkim_domain',
          pattern: '^rendeles\\.gymbeam\\.hu$',
          required: true,
          source_ids: ['gymbeam-observed-legacy-auth'],
        },
        {
          id: 'gymbeam.invoice-legacy.subject',
          field: 'subject',
          pattern: 'sz[aá]ml[aá]d\\s+a\\s+\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sedhez',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
        {
          id: 'gymbeam.invoice-legacy.document',
          field: 'body',
          pattern: '\\d{10,12}\\s+sz[aá]m[uú]\\s+elektronikus\\s+sz[aá]ml[aá]dat\\s+a\\s+\\d{10}\\s+sz[aá]m[uú]\\s+rendel[eé]sedhez',
          required: true,
          source_ids: ['gymbeam-observed-legacy-paid-invoice'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE'],
    },
  ],
  notes: [
    'The current GymBeam subject equivalent to "your order is on the way" is not physical SHIPPED evidence when the body explicitly says the parcel was only packed and will soon be handed to the carrier. Body semantics win over subject marketing copy.',
    'Direct Express One / GLS / Foxpost evidence outranks GymBeam merchant logistics wording for physical movement, delivery failure, pickup and final delivery.',
    'The legacy paid-order invoice email is lower-authority merchant PAYMENT_SUCCESS evidence because it explicitly says GymBeam received the amount due and the order is already paid. Direct payment-provider evidence remains stronger when available.',
    'The current invoice-ready email can say everything is paid, but V1 deliberately does not turn that status summary into a separate payment-success event. PAYMENT_SUCCESS requires the stronger observed legacy receipt-of-funds wording.',
    'Invoice email can prove INVOICE and carry explicit order/invoice identity, but it must never create a Purchase by itself.',
    'No positive CANCELLED, PAYMENT_FAILED, RETURN, REFUNDED, WARRANTY, DELIVERED or READY_FOR_PICKUP email rule is implemented without a verified direct recipient template.',
    'Human support replies and Trustpilot/review campaigns are not automated GymBeam merchant lifecycle authority.',
    'Existing deterministic GymBeam runtime adapters predate this Protocol Library profile. This shadow profile formalizes and regression-checks observed semantics; it does not activate new production protocol decisions.',
  ],
};
