import type { ProtocolProfile } from '../types.js';

/**
 * Merchant-specific Shoprenter profile derived from a sanitized, observed
 * Home Automatica customer journey.
 *
 * The observed journey is especially useful because it contains both payment
 * failure and recovery plus a merchant pre-advice status that was immediately
 * corroborated by a direct FOXPOST pre-advice saying the parcel had NOT yet
 * been handed to FOXPOST.
 */
export const HOMEAUTOMATICA_SHOPRENTER_TEST_V1: ProtocolProfile = {
  protocol_id: 'merchant.hu.homeautomatica',
  protocol_version: '1.0.0-test.1',
  kind: 'merchant',
  status: 'test',
  display_name: 'Home Automatica Kft (Shoprenter)',
  country: 'HU',
  sender_domains: ['homeautomatica.hu'],
  sender_addresses: ['info@homeautomatica.hu'],
  identifier_patterns: {
    order_id: [
      'Rendel[eé]ssz[aá]m\\s*:\\s*#?([0-9]{3,10})',
      'A\\(z\\)\\s*#?([0-9]{3,10})\\.?\\s*sz[aá]m[uú] rendel[eé]st',
      'a\\(z\\)\\s*#?([0-9]{3,10})\\.?\\s*sz[aá]m[uú] rendel[eé]s [aá]llapota',
      '^Rendel[eé]s\\s+([0-9]{3,10})$',
    ],
    tracking_id: [],
    invoice_id: [],
    payment_reference: [
      'Tranzakci[oó] azonos[ií]t[oó]\\s*:\\s*([A-Za-z0-9._-]+)',
    ],
  },
  sources: [
    {
      id: 'shoprenter-official-emails',
      title: 'Shoprenter automatic email documentation',
      url: 'https://support.shoprenter.hu/hc/hu/articles/215106278-Automatikus-emailek',
      provenance: 'official_documentation',
    },
    {
      id: 'homeautomatica-observed-order-confirmation',
      title: 'Observed Home Automatica order confirmation (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Verified merchant sender plus Shoprenter DKIM/return-path infrastructure and rendered order-confirmation structure. Private customer data and the real order id are not stored.',
    },
    {
      id: 'homeautomatica-observed-payment-failed',
      title: 'Observed Home Automatica failed-card-payment email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Explicit failed payment wording, transaction reference, non-success response code and response message. Private customer data and the real identifiers are not stored.',
    },
    {
      id: 'homeautomatica-observed-payment-success',
      title: 'Observed Home Automatica successful-card-payment email (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Explicit successful payment wording plus response code 00 and transaction accepted response. The merchant status changed to Jóváírás, proving this label is not a refund signal for this merchant.',
    },
    {
      id: 'homeautomatica-observed-foxpost-preparation',
      title: 'Observed Home Automatica FOXPOST preparation status (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Merchant status was FoxPost szállításra előkészítve. A direct FOXPOST pre-advice followed immediately and explicitly stated the parcel had not yet been handed to FOXPOST.',
    },
    {
      id: 'homeautomatica-observed-status-only',
      title: 'Observed Home Automatica merchant status-only emails (sanitized)',
      provenance: 'observed_real_email',
      observed_at: '2026-08-16',
      notes: 'Observed Jóváírás and Elküldve status-only messages contain stable order identity but no standalone proof of settled refund or physical carrier handoff.',
    },
  ],
  events: [
    {
      event: 'ORDER_CREATED',
      base_confidence: 0.95,
      positive_rules: [
        {
          id: 'ha.order.platform-dkim',
          field: 'dkim_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-order-confirmation'],
        },
        {
          id: 'ha.order.platform-return-path',
          field: 'return_path_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-order-confirmation'],
        },
        {
          id: 'ha.order.subject',
          field: 'subject',
          pattern: '^Rendel[eé]s\\s+[0-9]{3,10}$',
          required: true,
          source_ids: ['homeautomatica-observed-order-confirmation'],
        },
        {
          id: 'ha.order.confirmation-heading',
          field: 'body',
          pattern: 'RENDEL[EÉ]S VISSZAIGAZOL[AÁ]S',
          required: true,
          source_ids: ['homeautomatica-observed-order-confirmation'],
        },
        {
          id: 'ha.order.received-copy',
          field: 'body',
          pattern: 'Megrendel[eé]se meg[eé]rkezett, feldolgoz[aá]sa elkezd[oő]d[oö]tt',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['shoprenter-official-emails', 'homeautomatica-observed-order-confirmation'],
        },
        {
          id: 'ha.order.identity',
          field: 'body',
          pattern: 'Rendel[eé]ssz[aá]m\\s*:\\s*#?[0-9]{3,10}',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-order-confirmation'],
        },
      ],
    },
    {
      event: 'PAYMENT_FAILED',
      base_confidence: 0.96,
      positive_rules: [
        {
          id: 'ha.payment-failed.platform-dkim',
          field: 'dkim_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-failed'],
        },
        {
          id: 'ha.payment-failed.platform-return-path',
          field: 'return_path_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-failed'],
        },
        {
          id: 'ha.payment-failed.subject',
          field: 'subject',
          pattern: '^Sikertelen bankk[aá]rty[aá]s fizet[eé]s a Home Automatica Kft web[aá]ruh[aá]zban!$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-failed'],
        },
        {
          id: 'ha.payment-failed.order-copy',
          field: 'body',
          pattern: 'A\\(z\\)\\s*#?[0-9]{3,10}\\.?\\s*sz[aá]m[uú] rendel[eé]st nem siker[uü]lt befizetnie',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-payment-failed'],
        },
        {
          id: 'ha.payment-failed.transaction',
          field: 'body',
          pattern: 'A sikertelen fizet[eé]s adatai[\\s\\S]{0,240}Tranzakci[oó] azonos[ií]t[oó]\\s*:[\\s\\S]{0,120}V[aá]laszk[oó]d\\s*:\\s*(?!00\\b)[A-Za-z0-9._-]+[\\s\\S]{0,160}V[aá]lasz[uü]zenet\\s*:',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-payment-failed'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_AUTO_LINK'],
    },
    {
      event: 'PAYMENT_SUCCESS',
      base_confidence: 0.96,
      positive_rules: [
        {
          id: 'ha.payment-success.platform-dkim',
          field: 'dkim_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-success'],
        },
        {
          id: 'ha.payment-success.platform-return-path',
          field: 'return_path_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-success'],
        },
        {
          id: 'ha.payment-success.subject',
          field: 'subject',
          pattern: '^Sikeres bankk[aá]rty[aá]s fizet[eé]s a Home Automatica Kft web[aá]ruh[aá]zban!$',
          required: true,
          source_ids: ['homeautomatica-observed-payment-success'],
        },
        {
          id: 'ha.payment-success.order-copy',
          field: 'body',
          pattern: 'A\\(z\\)\\s*#?[0-9]{3,10}\\.?\\s*sz[aá]m[uú] rendel[eé]st sikeresen befizette',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-payment-success'],
        },
        {
          id: 'ha.payment-success.accepted-transaction',
          field: 'body',
          pattern: 'V[aá]laszk[oó]d\\s*:\\s*00\\b[\\s\\S]{0,180}V[aá]lasz[uü]zenet\\s*:\\s*Tranzakci[oó] elfogadva',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-payment-success'],
        },
      ],
      prohibitions: ['DO_NOT_CREATE_PURCHASE', 'DO_NOT_AUTO_LINK'],
    },
    {
      event: 'SHIPMENT_CREATED',
      base_confidence: 0.97,
      positive_rules: [
        {
          id: 'ha.pre-advice.platform-dkim',
          field: 'dkim_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-foxpost-preparation'],
        },
        {
          id: 'ha.pre-advice.platform-return-path',
          field: 'return_path_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-foxpost-preparation'],
        },
        {
          id: 'ha.pre-advice.subject',
          field: 'subject',
          pattern: '^Home Automatica Kft\\s*[-–]\\s*a\\(z\\)\\s*[0-9]{3,10}\\.?\\s*sz[aá]m[uú] rendel[eé]s [aá]llapota megv[aá]ltozott$',
          required: true,
          source_ids: ['homeautomatica-observed-foxpost-preparation'],
        },
        {
          id: 'ha.pre-advice.identity',
          field: 'body',
          pattern: 'Rendel[eé]ssz[aá]m\\s*:\\s*#?[0-9]{3,10}',
          required: true,
          source_ids: ['homeautomatica-observed-foxpost-preparation'],
        },
        {
          id: 'ha.pre-advice.explicit-status',
          field: 'body',
          pattern: 'jelenlegi [aá]llapot\\s*:\\s*FoxPost sz[aá]ll[ií]t[aá]sra el[oő]k[eé]sz[ií]tve',
          required: true,
          confidence_delta: 0.03,
          source_ids: ['homeautomatica-observed-foxpost-preparation'],
        },
      ],
      prohibitions: [
        'DO_NOT_CREATE_PURCHASE',
        'DO_NOT_AUTO_LINK',
        'DO_NOT_SET_SHIPPED_AT',
        'DO_NOT_MARK_IN_TRANSIT',
        'DO_NOT_MARK_DELIVERED',
      ],
    },
    {
      event: 'OTHER',
      base_confidence: 0.93,
      positive_rules: [
        {
          id: 'ha.status-only.platform-dkim',
          field: 'dkim_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-status-only'],
        },
        {
          id: 'ha.status-only.platform-return-path',
          field: 'return_path_domain',
          pattern: '^(?:[a-z0-9-]+\\.)?smtp\\.shoprenter\\.hu$',
          required: true,
          source_ids: ['homeautomatica-observed-status-only'],
        },
        {
          id: 'ha.status-only.subject',
          field: 'subject',
          pattern: '^Home Automatica Kft\\s*[-–]\\s*a\\(z\\)\\s*[0-9]{3,10}\\.?\\s*sz[aá]m[uú] rendel[eé]s [aá]llapota megv[aá]ltozott$',
          required: true,
          source_ids: ['homeautomatica-observed-status-only'],
        },
        {
          id: 'ha.status-only.identity',
          field: 'body',
          pattern: 'Rendel[eé]ssz[aá]m\\s*:\\s*#?[0-9]{3,10}',
          required: true,
          source_ids: ['homeautomatica-observed-status-only'],
        },
        {
          id: 'ha.status-only.safe-labels',
          field: 'body',
          pattern: 'jelenlegi [aá]llapot\\s*:\\s*(?:J[oó]v[aá][ií]r[aá]s|Elk[uü]ldve)',
          required: true,
          confidence_delta: 0.02,
          source_ids: ['homeautomatica-observed-status-only', 'homeautomatica-observed-payment-success'],
        },
      ],
      prohibitions: [
        'DO_NOT_CREATE_PURCHASE',
        'DO_NOT_AUTO_LINK',
        'DO_NOT_SET_SHIPPED_AT',
        'DO_NOT_MARK_IN_TRANSIT',
        'DO_NOT_MARK_DELIVERED',
        'DO_NOT_MARK_REFUNDED',
      ],
    },
  ],
  notes: [
    'Home Automatica uses the same observed Shoprenter DKIM and return-path infrastructure as another independently observed Shoprenter merchant, strengthening platform-level infrastructure evidence.',
    'The merchant order id observed here is only three digits. Lifecycle events therefore carry DO_NOT_AUTO_LINK until a separate resolver provides stronger identity corroboration.',
    'Jóváírás must not be interpreted as REFUNDED for this merchant: in the observed journey it is the status reached immediately after an explicitly successful card payment.',
    'FoxPost szállításra előkészítve is SHIPMENT_CREATED only. Direct FOXPOST pre-advice explicitly said the parcel had not yet been handed to the carrier.',
    'Elküldve is intentionally OTHER when seen only in the merchant status email. Direct carrier evidence is required before asserting physical SHIPPED or later logistics progress.',
    'The profile is shadow-only. status=test means none of these candidates can become production_eligible or write live state.',
  ],
};
