from __future__ import annotations

PHRASES: dict[str, dict[str, str]] = {
    "ORDER_CREATED": {
        "hu": "A v\u00e1s\u00e1rl\u00e1si k\u00e9relmet r\u00f6gz\u00edtett\u00fck, \u00e9s \u00faj rendel\u00e9sk\u00e9nt beker\u00fclt a rendszerbe.",
        "en": "We logged this purchase as a new order in our system.",
        "de": "Der Einkauf wurde als neue Bestellung in unserem System erfasst.",
        "pl": "Zakup zosta\u0142 zapisany w systemie jako nowe zam\u00f3wienie.",
        "fr": "Cet achat a \u00e9t\u00e9 enregistr\u00e9 dans notre syst\u00e8me comme une nouvelle commande.",
        "es": "La compra ha quedado registrada en el sistema como un pedido nuevo.",
    },
    "ORDER_PROCESSING": {
        "hu": "A rendel\u00e9s nyitva van, jelenleg az adatok \u00e9s a k\u00e9szlet ellen\u0151rz\u00e9se zajlik.",
        "en": "The order remains open while stock and order details are being checked.",
        "de": "Die Bestellung ist offen; Bestand und Bestelldaten werden derzeit gepr\u00fcft.",
        "pl": "Zam\u00f3wienie jest otwarte; trwa weryfikacja danych i dost\u0119pno\u015bci towaru.",
        "fr": "La commande reste ouverte pendant la v\u00e9rification du stock et des informations.",
        "es": "El pedido sigue abierto mientras se comprueban existencias y datos.",
    },
    "ORDER_PACKING": {
        "hu": "A rakt\u00e1r \u00f6sszek\u00e9sz\u00edti \u00e9s dobozolja a rendel\u00e9st; fuvaroz\u00f3i \u00e1tv\u00e9tel m\u00e9g nem t\u00f6rt\u00e9nt.",
        "en": "The warehouse is boxing the order; no carrier pickup has happened yet.",
        "de": "Das Lager verpackt die Bestellung; eine Abholung durch den Versanddienstleister gab es noch nicht.",
        "pl": "Magazyn pakuje zam\u00f3wienie; przewo\u017anik jeszcze go nie odebra\u0142.",
        "fr": "L'entrep\u00f4t emballe la commande; le transporteur ne l'a pas encore collect\u00e9e.",
        "es": "El almac\u00e9n est\u00e1 empaquetando el pedido; el transportista a\u00fan no lo ha recogido.",
    },
    "SHIPMENT_CREATED": {
        "hu": "A sz\u00e1ll\u00edt\u00e1si c\u00edmke elk\u00e9sz\u00fclt, de a fut\u00e1r m\u00e9g nem szkennelte \u00e1t fizikailag a csomagot.",
        "en": "A shipping label now exists, but the carrier has not physically scanned the parcel yet.",
        "de": "Das Versandlabel wurde erstellt, aber der Dienstleister hat das Paket noch nicht physisch gescannt.",
        "pl": "Etykieta wysy\u0142kowa zosta\u0142a utworzona, ale przewo\u017anik nie zeskanowa\u0142 jeszcze fizycznie paczki.",
        "fr": "L'\u00e9tiquette d'exp\u00e9dition existe, mais le transporteur n'a pas encore scann\u00e9 physiquement le colis.",
        "es": "La etiqueta de env\u00edo ya existe, pero el transportista a\u00fan no ha escaneado f\u00edsicamente el paquete.",
    },
    "SHIPPED": {
        "hu": "A felad\u00e1si ponton megt\u00f6rt\u00e9nt az els\u0151 fizikai \u00e1tv\u00e9teli szkennel\u00e9s a fut\u00e1r h\u00e1l\u00f3zat\u00e1ban.",
        "en": "The carrier recorded the first physical acceptance scan at origin.",
        "de": "Am Ausgangspunkt wurde der erste physische Annahmescan des Versanddienstleisters erfasst.",
        "pl": "Przewo\u017anik zarejestrowa\u0142 pierwszy fizyczny skan przyj\u0119cia w punkcie nadania.",
        "fr": "Le transporteur a enregistr\u00e9 le premier scan physique de prise en charge au d\u00e9part.",
        "es": "El transportista registr\u00f3 el primer escaneo f\u00edsico de aceptaci\u00f3n en origen.",
    },
    "IN_TRANSIT": {
        "hu": "A k\u00fcldem\u00e9ny elhagyta az eloszt\u00f3k\u00f6zpontot, \u00e9s a k\u00f6vetkez\u0151 logisztikai \u00e1llom\u00e1s fel\u00e9 halad.",
        "en": "The parcel departed a sorting facility and is moving to the next network location.",
        "de": "Das Paket hat ein Sortierzentrum verlassen und ist auf dem Weg zum n\u00e4chsten Netzknoten.",
        "pl": "Paczka opu\u015bci\u0142a sortowni\u0119 i jedzie do kolejnego punktu sieci logistycznej.",
        "fr": "Le colis a quitt\u00e9 un centre de tri et se dirige vers l'\u00e9tape logistique suivante.",
        "es": "El paquete sali\u00f3 de un centro de clasificaci\u00f3n y avanza al siguiente punto de la red.",
    },
    "OUT_FOR_DELIVERY": {
        "hu": "A csomagot felrakt\u00e1k a k\u00e9zbes\u00edt\u0151 j\u00e1rm\u0171re; a fut\u00e1r a c\u00edmzett fel\u00e9 tart vele.",
        "en": "The parcel is loaded on the delivery vehicle and the courier is heading to the recipient.",
        "de": "Das Paket wurde in das Zustellfahrzeug geladen; der Fahrer ist zum Empf\u00e4nger unterwegs.",
        "pl": "Paczka jest w samochodzie dor\u0119czyciela, kt\u00f3ry jedzie do odbiorcy.",
        "fr": "Le colis est charg\u00e9 dans le v\u00e9hicule de livraison et le livreur se dirige vers le destinataire.",
        "es": "El paquete va en el veh\u00edculo de reparto y el mensajero se dirige al destinatario.",
    },
    "READY_FOR_PICKUP": {
        "hu": "Az \u00e1tv\u00e9teli PIN aktiv\u00e1l\u00f3dott; a csomag m\u00e1r a kiv\u00e1lasztott automat\u00e1ban v\u00e1r.",
        "en": "The pickup PIN is active and the parcel is waiting inside the selected locker.",
        "de": "Die Abhol-PIN ist aktiv; das Paket liegt bereits im ausgew\u00e4hlten Automaten.",
        "pl": "Kod odbioru jest aktywny, a paczka czeka ju\u017c w wybranym automacie.",
        "fr": "Le code de retrait est actif et le colis attend d\u00e9j\u00e0 dans la consigne choisie.",
        "es": "El PIN de recogida est\u00e1 activo y el paquete ya espera en la taquilla seleccionada.",
    },
    "DELIVERED": {
        "hu": "A c\u00edmzett \u00e1tv\u00e9tel\u00e9t r\u00f6gz\u00edtett\u00fck; a k\u00e9zbes\u00edt\u00e9s lez\u00e1rult.",
        "en": "Recipient acceptance was recorded and the delivery is closed.",
        "de": "Die Annahme durch den Empf\u00e4nger wurde erfasst; die Zustellung ist abgeschlossen.",
        "pl": "Odbi\u00f3r przez adresata zosta\u0142 potwierdzony; dor\u0119czenie jest zako\u0144czone.",
        "fr": "La r\u00e9ception par le destinataire a \u00e9t\u00e9 enregistr\u00e9e; la livraison est termin\u00e9e.",
        "es": "Se registr\u00f3 la recepci\u00f3n por el destinatario y la entrega ha finalizado.",
    },
    "DELIVERY_FAILED": {
        "hu": "A mai k\u00e9zbes\u00edt\u00e9si k\u00eds\u00e9rlet sikertelen volt, ez\u00e9rt \u00faj k\u00e9zbes\u00edt\u00e9si l\u00e9p\u00e9s sz\u00fcks\u00e9ges.",
        "en": "Today's delivery attempt failed and another delivery action is required.",
        "de": "Der heutige Zustellversuch ist fehlgeschlagen; ein weiterer Zustellschritt ist erforderlich.",
        "pl": "Dzisiejsza pr\u00f3ba dor\u0119czenia nie powiod\u0142a si\u0119 i potrzebne jest kolejne dzia\u0142anie.",
        "fr": "La tentative de livraison d'aujourd'hui a \u00e9chou\u00e9; une nouvelle action est n\u00e9cessaire.",
        "es": "El intento de entrega de hoy fall\u00f3 y ser\u00e1 necesaria otra actuaci\u00f3n de reparto.",
    },
    "DELAYED": {
        "hu": "A sz\u00e1ll\u00edt\u00e1s cs\u00faszik, a v\u00e1rhat\u00f3 \u00e9rkez\u00e9si id\u0151 k\u00e9s\u0151bbre m\u00f3dosult, de \u00faj k\u00e9zbes\u00edt\u00e9si k\u00eds\u00e9rlet m\u00e9g nem t\u00f6rt\u00e9nt.",
        "en": "Transit is running late and the ETA moved later; no new delivery attempt has occurred.",
        "de": "Der Transport versp\u00e4tet sich und die ETA wurde nach hinten verschoben; ein neuer Zustellversuch fand noch nicht statt.",
        "pl": "Transport jest op\u00f3\u017aniony i termin przesuni\u0119to; nie by\u0142o jeszcze kolejnej pr\u00f3by dor\u0119czenia.",
        "fr": "Le transport est en retard et l'heure estim\u00e9e a \u00e9t\u00e9 repouss\u00e9e; aucune nouvelle tentative n'a eu lieu.",
        "es": "El transporte lleva retraso y la hora estimada se ha aplazado; a\u00fan no hubo otro intento de entrega.",
    },
    "CANCELLED": {
        "hu": "A keresked\u0151 \u00e9rv\u00e9nytelen\u00edtette a rendel\u00e9st; tov\u00e1bbi teljes\u00edt\u00e9s nem lesz.",
        "en": "The merchant voided the order and no further fulfillment will take place.",
        "de": "Der H\u00e4ndler hat die Bestellung aufgehoben; eine weitere Erf\u00fcllung findet nicht statt.",
        "pl": "Sprzedawca anulowa\u0142 zam\u00f3wienie i nie b\u0119dzie ono dalej realizowane.",
        "fr": "Le marchand a annul\u00e9 la commande; aucune ex\u00e9cution suppl\u00e9mentaire n'aura lieu.",
        "es": "El comercio anul\u00f3 el pedido y no continuar\u00e1 su preparaci\u00f3n.",
    },
    "REFUNDED": {
        "hu": "A j\u00f3v\u00e1\u00edr\u00e1st v\u00e9grehajtottuk az eredeti fizet\u00e9si m\u00f3dra; a visszat\u00e9r\u00edt\u00e9s p\u00e9nz\u00fcgyileg lez\u00e1rult.",
        "en": "Credit was issued back to the original payment method; the refund is financially complete.",
        "de": "Die Gutschrift wurde auf die urspr\u00fcngliche Zahlungsart ausgef\u00fchrt; die R\u00fcckerstattung ist abgeschlossen.",
        "pl": "\u015arodki zwr\u00f3cono na pierwotn\u0105 metod\u0119 p\u0142atno\u015bci; zwrot pieni\u0119dzy zosta\u0142 zako\u0144czony.",
        "fr": "Le cr\u00e9dit a \u00e9t\u00e9 renvoy\u00e9 vers le moyen de paiement initial; le remboursement est termin\u00e9.",
        "es": "El abono se envi\u00f3 al m\u00e9todo de pago original; el reembolso est\u00e1 completado.",
    },
    "PAYMENT": {
        "hu": "A k\u00e1rtyaterhel\u00e9st elfogadtuk \u00e9s k\u00f6nyvelt\u00fck; a fizet\u00e9si tranzakci\u00f3 sikeresen lez\u00e1rult.",
        "en": "The card charge was accepted and captured; the payment transaction is complete.",
        "de": "Die Kartenbelastung wurde akzeptiert und verbucht; die Zahlungstransaktion ist abgeschlossen.",
        "pl": "Obci\u0105\u017cenie karty zosta\u0142o zaakceptowane i zaksi\u0119gowane; p\u0142atno\u015b\u0107 jest zako\u0144czona.",
        "fr": "Le d\u00e9bit de carte a \u00e9t\u00e9 accept\u00e9 et comptabilis\u00e9; la transaction de paiement est termin\u00e9e.",
        "es": "El cargo en la tarjeta fue aceptado y contabilizado; la transacci\u00f3n de pago ha finalizado.",
    },
    "INVOICE": {
        "hu": "Az ad\u00f3\u00fcgyi sz\u00e1mla ki\u00e1ll\u00edt\u00e1sa megt\u00f6rt\u00e9nt, \u00e9s a PDF dokumentum el\u00e9rhet\u0151.",
        "en": "The tax invoice has been issued and its PDF document is available.",
        "de": "Die Steuerrechnung wurde ausgestellt und das PDF-Dokument ist verf\u00fcgbar.",
        "pl": "Faktura zosta\u0142a wystawiona, a dokument PDF jest dost\u0119pny.",
        "fr": "La facture fiscale a \u00e9t\u00e9 \u00e9mise et le document PDF est disponible.",
        "es": "La factura fiscal ha sido emitida y el documento PDF est\u00e1 disponible.",
    },
    "RETURN": {
        "hu": "A visszak\u00fcld\u00e9si \u00fcgyet megnyitottuk \u00e9s a visszak\u00fcld\u00e9si c\u00edmke elk\u00e9sz\u00fclt; p\u00e9nzvisszat\u00e9r\u00edt\u00e9s m\u00e9g nem t\u00f6rt\u00e9nt.",
        "en": "A return case is open and the return label is ready; no refund has been issued yet.",
        "de": "Der R\u00fccksendefall ist er\u00f6ffnet und das R\u00fccksendeetikett liegt vor; eine Erstattung wurde noch nicht ausgef\u00fchrt.",
        "pl": "Sprawa zwrotu jest otwarta i etykieta zwrotna gotowa; pieni\u0119dzy jeszcze nie zwr\u00f3cono.",
        "fr": "Le dossier de retour est ouvert et l'\u00e9tiquette est pr\u00eate; aucun remboursement n'a encore \u00e9t\u00e9 effectu\u00e9.",
        "es": "El caso de devoluci\u00f3n est\u00e1 abierto y la etiqueta est\u00e1 lista; todav\u00eda no se ha emitido ning\u00fan reembolso.",
    },
    "WARRANTY": {
        "hu": "RMA \u00fcgyet nyitottunk, \u00e9s a term\u00e9ket garanci\u00e1lis bevizsg\u00e1l\u00e1sra befogadtuk.",
        "en": "An RMA case was opened and the product was accepted for warranty inspection.",
        "de": "Ein RMA-Fall wurde er\u00f6ffnet und das Produkt zur Garantiepr\u00fcfung angenommen.",
        "pl": "Otwarto spraw\u0119 RMA, a produkt przyj\u0119to do diagnostyki gwarancyjnej.",
        "fr": "Un dossier RMA a \u00e9t\u00e9 ouvert et le produit accept\u00e9 pour contr\u00f4le sous garantie.",
        "es": "Se abri\u00f3 un caso RMA y el producto fue aceptado para revisi\u00f3n en garant\u00eda.",
    },
    "OTHER": {
        "hu": "\u00daj bejelentkez\u00e9st \u00e9szlelt\u00fcnk a fi\u00f3kban; ha \u00d6n volt, nincs tov\u00e1bbi teend\u0151.",
        "en": "A new sign-in was detected on your account; no action is needed if it was you.",
        "de": "Eine neue Anmeldung an Ihrem Konto wurde erkannt; wenn Sie es waren, ist nichts weiter zu tun.",
        "pl": "Wykryto nowe logowanie do konta; je\u015bli to Ty, nie musisz nic robi\u0107.",
        "fr": "Une nouvelle connexion \u00e0 votre compte a \u00e9t\u00e9 d\u00e9tect\u00e9e; aucune action n'est requise si c'\u00e9tait vous.",
        "es": "Se detect\u00f3 un nuevo inicio de sesi\u00f3n en tu cuenta; si fuiste t\u00fa, no hace falta hacer nada.",
    },
}

CONFUSER = {
    "ORDER_CREATED": "ORDER_PROCESSING",
    "ORDER_PROCESSING": "ORDER_PACKING",
    "ORDER_PACKING": "SHIPMENT_CREATED",
    "SHIPMENT_CREATED": "SHIPPED",
    "SHIPPED": "IN_TRANSIT",
    "IN_TRANSIT": "OUT_FOR_DELIVERY",
    "OUT_FOR_DELIVERY": "DELIVERED",
    "READY_FOR_PICKUP": "DELIVERED",
    "DELIVERED": "OUT_FOR_DELIVERY",
    "DELIVERY_FAILED": "DELAYED",
    "DELAYED": "DELIVERY_FAILED",
    "CANCELLED": "REFUNDED",
    "REFUNDED": "RETURN",
    "PAYMENT": "INVOICE",
    "INVOICE": "PAYMENT",
    "RETURN": "REFUNDED",
    "WARRANTY": "RETURN",
    "OTHER": "ORDER_CREATED",
}

FAMILY = {
    "ORDER_CREATED": "order-root-vs-processing",
    "ORDER_PROCESSING": "processing-vs-packing",
    "ORDER_PACKING": "packing-vs-shipment-created",
    "SHIPMENT_CREATED": "label-created-vs-physical-handoff",
    "SHIPPED": "physical-handoff-vs-transit",
    "IN_TRANSIT": "transit-vs-last-mile",
    "OUT_FOR_DELIVERY": "last-mile-vs-delivered",
    "READY_FOR_PICKUP": "pickup-ready-vs-delivered",
    "DELIVERED": "delivered-vs-out-for-delivery",
    "DELIVERY_FAILED": "failed-attempt-vs-delay",
    "DELAYED": "delay-vs-failed-attempt",
    "CANCELLED": "cancelled-vs-refunded",
    "REFUNDED": "refund-complete-vs-return-open",
    "PAYMENT": "payment-vs-invoice",
    "INVOICE": "invoice-vs-payment",
    "RETURN": "return-open-vs-refund-complete",
    "WARRANTY": "warranty-claim-vs-return",
    "OTHER": "non-commerce-trap",
}

MERCHANTS = ["Aurora Retail", "Kite Market", "Orchid Store", "Delta Goods", "Copper Cart", "Mosaic Shop"]
CARRIERS = ["North Parcel", "Arrow Courier", "Transit Bee", "Rapid Route", "Parcel Works", "City Drop"]
